const API_STATUS_CODES = {
    SUCCESS: 200,
    AUTHORIZATION_FAILED: 401,
    INTERNAL_SERVER_ERROR: 500,
    DUPLICATE_ENTRY: 11000,
    ERROR_CODE: 400,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
    CREATED: 201,
    USER_NOT_VERIFIED: 403,
    DEAL_NOT_TRIED: 403,
    INTERNAL_ERROR: 500,
};

const RESPONSE_MESSAGES = {

    FILTER_NOT_FOUND: "filter is not applied",
    DEAL_NOT_FOUND: "deal is not found",
    DEAL_NOT_TRIED: "You can only review deals you have tried",
    USER_NOT_VERIFIED: " User is not verified by otp. please verify your email , I sent to your email ",
    FIELD_REQUIRED: "All fields are required",
    SHOP_NOT_FOUND: "shop are found",
    EMAIL_REQUIRED: "Please provide a valid email address",
    INVALID_EMAIL: "Please provide a valid email address",
    INVALID_PHONE: "Please provide a valid phone number",
    INVALID_PASSWORD: "Password must be at least 6 characters long",
    SHOP_NOT_FOUND: "shop is not found",
    OYSTER_NOT_FOUND: "oyster is not found",

    USER_REGISTERED_SUCCESS: "User registered successfully",
    USER_ALREADY_EXISTS: "User with this email already exists",
    INTERNAL_SERVER_ERROR: "Internal server error",
    EMAIL_AND_PASSWORD_REQUIRED: "Email and password are required",
    LOGIN_SUCCESS: "Login successful",
    INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
    USER_UPDATED_SUCCESS: "User updated successfully",
    USER_DELETED_SUCCESS: "User deleted successfully",
    USER_NOT_FOUND: "User not found",
    USER_NOT_FOUND_OR_INVALID_PASSWORD: "User not found or invalid password",
    TOKEN_REFRESHED_SUCCESS: "Access token refreshed successfully",
    INVALID_REFRESH_TOKEN: "Invalid refresh token",
    LOGOUT_SUCCESS: "Logout successful",
    TOKEN_EXPIRED: "Token expired",
    ACCESS_DENIED: "Access denied",
    POST_NOT_FOUND: "Post not found",
    UNAUTHORIZED_ACCESS: "You are not authorized to perform this action",
    POST_CREATED_SUCCESS: "Post created successfully",
    POST_UPDATED_SUCCESS: "Post updated successfully",
    POST_DELETED_SUCCESS: "Post deleted successfully",
    ALREADY_LIKED: "You have already liked this post",
    NOT_LIKED: "You have not liked this post",
    POST_LIKED_SUCCESS: "Post liked successfully",
    POST_DISLIKED_SUCCESS: "Post disliked successfully",
    POST_SAVED_SUCCESS: "Post saved/favourite successfully",
    POST_UNSAVED_SUCCESS: "Post unsaved/unfavourite successfully",
    STATS_NOT_FOUND: "Stats not found",
    TOTAL_STATS_SUCCESS: "Total stats fetched successfully",
    ALREADY_SAVED: "You have already saved this post",
    NOT_SAVED: "You have not saved this post",
    COMMENT_CREATED: "comment is created succesfully",
    COMMENT_UPDATED: "comment is updated succesfully",
    COMMENT_NOTFOUND: "comment is created succesfully",
    COMMENT_DELETED: "comment is deleted succesfully",
    COMMENT_NOT_INDB: "comment is not found in db",
    COMMENT_NOT_FOUND: "comment is not found",
    COMMENT_DELETED_SUCCESS: "comment is deleted successfully",
    // Password reset messages
    OTP_SENT_SUCCESS: "OTP sent successfully to your email",
    OTP_VERIFIED_SUCCESS: "OTP verified successfully",
    INVALID_OTP: "Invalid OTP or OTP expired",
    PASSWORD_RESET_SUCCESS: "Password reset successfully",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
    OTP_REQUIRED: "OTP is required",
    CONFIRM_PASSWORD_REQUIRED: "Confirm password is required",
    NEW_PASSWORD_REQUIRED: "New password is required",
    EMAIL_SEND_FAILED: "Email send failed",
    EMAIL_SEND_SUCCESS: "Email send successfully",

    //cloudinary error messages
    IMAGE_NOT_UPLOADED: "image is not uploaded ",

};

module.exports = {
    API_STATUS_CODES,
    RESPONSE_MESSAGES
};

